name: Build Unity Windows Executable

on:
  push:
    branches:
      - main
      - master

jobs:
  buildForWindows:
    name: Build for Windows Standalone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Dummy Scene
        run: |
          mkdir -p Assets/Scenes
          echo 'fileFormatVersion: 2' > Assets/Scenes/Main.unity

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ""
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: 2022.3.20f1

      - name: Upload Windows Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LoofyHorror-Windows-Build
          path: build/StandaloneWindows64
          
